eureka: 
  client: 
    healthcheck: 
      enabled: true
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka/"
  instance: 
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1
ribbon: 
  eureka: 
    enabled: false
server: 
  port: 7111
spring:  
  application:
    name: bank-service  