endpoints: 
  health: 
    sensitive: false
  restart: 
    enabled: true
  shutdown: 
    enabled: true
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka/"
info: 
  component: "Edge Server"
logging: 
  level: 
    ROOT: INFO
    org.springframework.web: DEBUG
ribbon: 
  eureka: 
    enabled: true
server: 
  port: 8765
zuul: 
  prefix: /api
  routes: 
    bank-service: 
      path: /bank-service/**
      serviceId: bank-service
    static: 
      path: /static/**
    test: 
      path: /redirect/**
      url: "http://google.com"