error: 
  whitelabel: 
    enabled: false
eureka: 
  client: 
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka/"
  server: 
    enableSelfPreservation: false
server: 
  port: 8761
spring: 
  application: 
    name: recharge-registry
